

const apiPath = Object.freeze({
loginUser:"/auth/login",
getallUsers:"/api/users",
sendMessage:"/api/messages/send",
getMessages:"/api/messages",




    loginadmin: "/admins/auth/login",
    students: "/studetns",
    classes: "/admins/classes/get/all",
    classesByNames: "/admins/classes/classnames",
    createClassess: "/admins/classes/reg",
    updateClass: "/admins/classes/update/class",
    clssToggle: "/admins/classes/class/status",
    getSubjects: "/admins/classes/get/subjects",
    getSubjectsByClassname: "/admins/classes/subjects",
    getSubjectByClassnameSectionWise: "/admins/classes/subjectSection",
    deleteBannerImage: "/admins/setting/Delete",
    ToggleSubject: "/admins/classes/subject/status",
    createSubject: "/admins/classes/subjects/reg",
    updateSubject: "/admins/classes/update/subject",
    deleteSubject: "/admins/classes/delete/subject",
    getStudents: "/admins/students/get/all",
    getParticularStudent: "/admins/students/get/student/profile",
    studentReg: "/admins/students/reg",
    studentDelete: "/admins/students/delete",
    updateStudent: "/admins/students/update",
    createTeacher: "/admins/teachers/register",
    getTeachers: "/admins/teachers/getAllTeacher",
    getParticularTeacher: "/admins/teachers/getTeacherProfile",
    updateTeacher: "/admins/teachers/update-teacher",
    deleteTeacher: "/admins/teachers/soft-delete",
    getParticularTeacher: "/admins/teachers/get-profile",
    dashboardData: "/admins/dashboard",
    SchoolSettings: "/admins/setting/school-settings",
    createSchoolSettings: "/admins/setting/school-settings",
    updateSchoolSettings: "/admins/setting/update-settings",
    resetSchoolSettings: "/admins/setting/school-settings/reset",
    getAdminProfile: "/admins/auth/profile",
    updateAdminProfile: "/admins/auth/edit-profile",
    createFeesStructure: "/admins/fees/structure",
    getFeesStructure: "/admins/fees/get/fee-structure",
    updateFeesStructure: "/admins/fees/update/fee-structure",
    deleteFeesStructure: "/admins/fees/delete/fee-structure",
    getAllFees: "/admins/fees/get/all",
    feestoggleFeesStructure: "/admins/fees/toggle/status/fee-structure",
    AddFees: "/admins/fees/student",
    getSettings: "admins/setting/school-settings",
    getAssignments: "admins/timetable",
    postAssignmentBulk: "admins/timetable/assign",
    verifyAssignment: "admins/timetable/check",
    resetAssign: "admins/timetable/reset",
    teacherAttendance: "admins/teachers/attendance",
    resetPassword: "admins/auth/forgot-password",
    LinkresetApi: "admins/auth/reset-password",
    TeacherSalary: "admins/teachersalary/salary-status",
    AddClassTeacher: "admins/teachers/class-teacherOf",
    generateTeacherSalary: "/admins/teachersalary/generate-salary",
    importStudents: "/admins/students/bulk-upload",
    getIpAddress: "/admins/ipAddress/getipAddress",
    registerIp: "/admins/ipAddress/register/ipAddress",
    updateIp: "/admins/ipAddress/updateipAddress",
    deleteIp: "/admins/ipAddress/deleteipAddress",
    getHolidays: "/admins/calender/getholidays",
    holidays: "/admins/calender/holidays-calender",
    holidaysUpdate: "/admins/calender/update",
    holidaysDelete: "/admins/calender/delete",
    getAttendanceClockwise: "/admins/teachers/get-all-attendance",
    updateClockwiseAttendance: "/admins/teachers/update-attendance",
    importTeacher: "/admins/teachers/bulk-upload",
    importCalander: "/admins/calender/bulk-upload",
    getallTeachers: "/admins/teachers/allteachers",
    inquiryList: "/admins/auth/contacts",
    galleryCategories: "/admins/setting/get",
    createCategorySetting: "/admins/setting/add",
    deleteCategorySettings: "/admins/setting/category/delete",
    updateCategorySetting: "/admins/setting/update",
    uploadImageGallery: "/admins/setting/category/upload-images",
    gallerySettingGetImages: "/admins/setting/get-images",
    GallerySettingDeleteImage: "/admins/setting/Delete-images",
    createLeader: "/leadership/addleader",
    createAboutUsSection: "/admins/about",
    GetAboutSection: "/admins/about",
    updateAboutSection: "/admins/about",
    getAllLeaders: "/leadership/allleader",
    updateLeaderInfo: "/leadership/updateleader",
    deleteLeaderInfo: "/leadership/deleteleader",
    aboutinfoDelete: "/admins/about"



});

export default apiPath;
